kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
  - linuxkit/ca-certificates:d96dc58b359b791553028cc338576a2556eef4fc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:af10b5180ce0943a2fbad61f1ebf9f24ae76d866
services:
  - name: dhcpcd
    image: linuxkit/dhcpcd:02ee79dcaa2e88b82b7aeafa178af6da39982deb
  - name: getty
    image: linuxkit/getty:6a416caac6476deaafac944a0d6528a49ea44744
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
