kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
  - linuxkit/ca-certificates:d96dc58b359b791553028cc338576a2556eef4fc
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:af10b5180ce0943a2fbad61f1ebf9f24ae76d866
  - name: dhcpcd
    image: linuxkit/dhcpcd:02ee79dcaa2e88b82b7aeafa178af6da39982deb
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:6f07422f40b943f10e5282665ff2a663b99f241a
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
