kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
  - linuxkit/ca-certificates:d96dc58b359b791553028cc338576a2556eef4fc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:af10b5180ce0943a2fbad61f1ebf9f24ae76d866
  - name: dhcpcd
    image: linuxkit/dhcpcd:02ee79dcaa2e88b82b7aeafa178af6da39982deb
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:3cc2755bbd134f7ba148fca97a4354c2ac8e3f8a
  - name: format
    image: linuxkit/format:a76845af039f8e41f1d846160e51882fe892b544
  - name: mount
    image: linuxkit/mount:67e0740f85dc6e08cc241d60cf4dc8fd2ae930b3
    command: ["/usr/bin/mountie", "/var/lib/docker"]

services:
  - name: getty
    image: linuxkit/getty:6a416caac6476deaafac944a0d6528a49ea44744
    env:
      - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:6f07422f40b943f10e5282665ff2a663b99f241a
  - name: ntpd
    image: linuxkit/openntpd:fd77c186a8a3e0ee41e82e4251bdad926ec03935

  - name: docker
    image: docker:20.10.6-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /var/run:/var/run
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: cadvisor
    image: linuxkit/cadvisor:ac4f1952c22200bd5ae3d5bd570eb7262860650d
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true, "hosts": ["unix:///var/run/docker.sock"]}'
    mode: "0644"
