kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
  - linuxkit/ca-certificates:d96dc58b359b791553028cc338576a2556eef4fc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:af10b5180ce0943a2fbad61f1ebf9f24ae76d866
  - name: dhcpcd
    image: linuxkit/dhcpcd:02ee79dcaa2e88b82b7aeafa178af6da39982deb
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:a76845af039f8e41f1d846160e51882fe892b544
    command: ["/usr/bin/format", "/dev/sda"]
  - name: mount
    image: linuxkit/mount:67e0740f85dc6e08cc241d60cf4dc8fd2ae930b3
    command: ["/usr/bin/mountie", "/dev/sda1", "/var/external"]
  - name: loop
    image: linuxkit/losetup:0ab60a230b4d20f130629bfc5d8314a129993b09
    command: ["/usr/bin/loopy", "--create", "/var/external/storage_file"]
  - name: dm-crypt
    image: linuxkit/dm-crypt:5d55e8026d2deefcc95391d2e069e50ce4aaeb10
    command: ["/usr/bin/crypto", "crypt_loop_dev", "/dev/loop0"]
  - name: mount
    image: linuxkit/mount:67e0740f85dc6e08cc241d60cf4dc8fd2ae930b3
    command: ["/usr/bin/mountie", "/dev/mapper/crypt_loop_dev", "/var/secure_storage"]
  - name: bbox
    image: busybox
    command: ["sh", "-c", "echo 'secret things' >/var/secure_storage/secrets"]
    binds:
      - /var:/var
services:
  - name: getty
    image: linuxkit/getty:6a416caac6476deaafac944a0d6528a49ea44744
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:6f07422f40b943f10e5282665ff2a663b99f241a
files:
  - path: etc/dm-crypt/key
    # the below key is just to keep the example self-contained
    # !!! provide a proper key for production use here !!!
    contents: "abcdefghijklmnopqrstuvwxyz123456"
