# This is an example for building the open source components of Docker for Mac
kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/vpnkit-expose-port:cbaaa0a12618c48563908068669fa33faf1d3a19 # install vpnkit-expose-port and vpnkit-iptables-wrapper on host
  - linuxkit/init:f7f97ead95502c2632fa884dd32a393afa55bafa
  - linuxkit/runc:b075ab467105ea77a903e4c25633476b5af02054
  - linuxkit/containerd:f392a0c758cca9c2dcf5d60dec2399f49c8eb6f2
  - linuxkit/ca-certificates:ec6a50d1d7110425b4b8d976647094b8d7b6c301
onboot:
  # support metadata for optional config in /run/config
  - name: metadata
    image: linuxkit/metadata:48c8cce4e29bef8c88b6752262d0b0f32309cb51
  - name: sysctl
    image: linuxkit/sysctl:cc3226a71bdd618fc96ec3f2d1a3d2fe1ac26d78
  - name: sysfs
    image: linuxkit/sysfs:7a30dee781650f320a2bf449bfd18e517476786a
  - name: binfmt
    image: linuxkit/binfmt:f8566c6b20524ccbbb7ef0f9299470ee1d325650
  # Format and mount the disk image in /var/lib/docker
  - name: format
    image: linuxkit/format:839a2e6108c545b6738d379b9182a57aab83ae68
  - name: mount
    image: linuxkit/mount:90b723bbe19fddd92aef45f7117761131c8f9186
    command: ["/usr/bin/mountie", "/var/lib"]
  # make a swap file on the mounted disk
  - name: swap
    image: linuxkit/swap:9c47dc60243bad6dabe905fb5f38807db2a27f6c
    command: ["/swap.sh", "--path", "/var/lib/swap", "--size", "1024M"]
  # mount-vpnkit mounts the 9p share used by vpnkit to coordinate port forwarding
  - name: mount-vpnkit
    image: alpine:3.13
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir -p /host_var/vpnkit/port && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
  # move logs to the mounted disk (this is a temporary fix until we can limit the log sizes)
  - name: move-logs
    image: alpine:3.13
    binds:
        - /var:/host_var
    command: ["sh", "-c", "mv -v /host_var/log /host_var/lib && ln -vs /var/lib/log /host_var/log"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:b8317b466095586c6629edc71f4d490d61ff72cf
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  # Enable acpi to shutdown on power events
  - name: acpid
    image: linuxkit/acpid:24a1872858b87820e5f9d1c0f10aff803257c465
  # Enable getty for easier debugging
  - name: getty
    image: linuxkit/getty:5628f6141f7e70d8ea8a715b91e7d258271724c0
    env:
        - INSECURE=true
  # Run ntpd to keep time synchronised in the VM
  - name: ntpd
    image: linuxkit/openntpd:b4025a6133c06d8f16fd003dfade828180525adc
  # VSOCK to unix domain socket forwarding. Forwards guest /var/run/docker.sock
  # to a socket on the host.
  - name: vsudd
    image: linuxkit/vsudd:99e385869c2b2acbd60be4eb4a1c2eeee36c8692
    binds:
        - /var/run:/var/run
    command: ["/vsudd", "-inport", "2376:unix:/var/run/docker.sock"]
  # vpnkit-forwarder forwards network traffic to/from the host via VSOCK port 62373. 
  # It needs access to the vpnkit 9P coordination share 
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:6925a1467b459636b72cf4fa75a0e08e70868a05
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder", "-vsockPort", "62373"]
  # Monitor for image deletes and invoke a TRIM on the container filesystem
  - name: trim-after-delete
    image: linuxkit/trim-after-delete:d8afb4e8cdb5229a7710e5225d23807e171f875c
  # When the host resumes from sleep, force a clock resync
  - name: host-timesync-daemon
    image: linuxkit/host-timesync-daemon:e69b84cac6166f878bb4acc1f5873aa7d9a8db39
  # Run dockerd with the vpnkit userland proxy from the vpnkit-forwarder container.
  # Bind mounts /var/run to allow vsudd to connect to docker.sock, /var/vpnkit
  # for vpnkit coordination and /run/config/docker for the configuration file.
  - name: docker-dfm
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/vpnkit:/port # vpnkit control 9p mount
     - /var/run:/var/run
     - /run/config/docker:/var/config/docker
     - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port # userland proxy
     - /usr/bin/vpnkit-iptables-wrapper:/usr/bin/iptables # iptables wrapper
    command: [ "/usr/local/bin/docker-init", "/usr/local/bin/dockerd", "--",
            "--config-file", "/var/config/docker/daemon.json",
            "--swarm-default-advertise-addr=eth0",
            "--userland-proxy-path", "/usr/bin/vpnkit-expose-port",
            "--storage-driver", "overlay2" ]
    runtime:
      mkdir: ["/var/lib/docker"]
