kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
  - linuxkit/ca-certificates:d96dc58b359b791553028cc338576a2556eef4fc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:af10b5180ce0943a2fbad61f1ebf9f24ae76d866
  - name: dhcpcd
    image: linuxkit/dhcpcd:02ee79dcaa2e88b82b7aeafa178af6da39982deb
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:6a416caac6476deaafac944a0d6528a49ea44744
    env:
     - INSECURE=true
    runtime:
      mounts:
        # Makes a writeable (but private and non-persistent) mount of the
        # host etc into the container.
        - type: overlay
          source: overlay
          destination: writeable-host-etc
          options: ["rw", "lowerdir=/etc", "upperdir=/run/hostetc/upper", "workdir=/run/hostetc/work"]
  - name: rngd
    image: linuxkit/rngd:6f07422f40b943f10e5282665ff2a663b99f241a
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
