# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:f7f97ead95502c2632fa884dd32a393afa55bafa
  - linuxkit/runc:b075ab467105ea77a903e4c25633476b5af02054
  - linuxkit/containerd:f392a0c758cca9c2dcf5d60dec2399f49c8eb6f2
  - linuxkit/ca-certificates:ec6a50d1d7110425b4b8d976647094b8d7b6c301
  - linuxkit/memlogd:e4f5d348f0721bfde577ab2035a513252ad9681f
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cc3226a71bdd618fc96ec3f2d1a3d2fe1ac26d78
  - name: dhcpcd
    image: linuxkit/dhcpcd:b8317b466095586c6629edc71f4d490d61ff72cf
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:5628f6141f7e70d8ea8a715b91e7d258271724c0
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:9627c383bab80018f0a53f98ab7ff7e80ce68f21
  - name: kmsg
    image: linuxkit/kmsg:a3cd697b6ca78e568fd1c3187df5494134dfafda
