kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:f7f97ead95502c2632fa884dd32a393afa55bafa
  - linuxkit/runc:b075ab467105ea77a903e4c25633476b5af02054
  - linuxkit/containerd:f392a0c758cca9c2dcf5d60dec2399f49c8eb6f2
  - linuxkit/ca-certificates:ec6a50d1d7110425b4b8d976647094b8d7b6c301
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cc3226a71bdd618fc96ec3f2d1a3d2fe1ac26d78
  - name: dhcpcd
    image: linuxkit/dhcpcd:b8317b466095586c6629edc71f4d490d61ff72cf
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:48c8cce4e29bef8c88b6752262d0b0f32309cb51
services:
  - name: getty
    image: linuxkit/getty:5628f6141f7e70d8ea8a715b91e7d258271724c0
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:160f9bfafae43b728ab58edd5f3aadc6128d2e55
  - name: sshd
    image: linuxkit/sshd:aec250026837fb2df7a9d64992edb9cfccfbdeb4
    binds.add:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
