kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:da8b633b6f6d0cb58b2302bd1ed54acee6d06245
  - linuxkit/runc:01a2389b9e2ebbb4642d95ce16a2a309c2f46c33
  - linuxkit/containerd:9e044bdf6ba20ac54c16cf756f0155a729b15e32
onboot:
  - name: ip
    image: linuxkit/ip:20e3848028eecd3e884a232816264a40e19046a9
    binds:
     - /etc/ip:/etc/ip
    command: ["ip", "-b", "/etc/ip/eth0.conf"]
services:
  - name: getty
    image: linuxkit/getty:6a416caac6476deaafac944a0d6528a49ea44744
    env:
     - INSECURE=true
files:     
  - path: etc/ip/eth0.conf
    contents: |
      address add 10.10.1.225/24 dev eth0
      link set eth0 up
      route add default via 10.10.1.100 dev eth0
  - path: etc/resolv.conf
    contents: |
#      domain test.local
      nameserver 10.10.1.101
      nameserver 10.10.1.100     
