kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:f7f97ead95502c2632fa884dd32a393afa55bafa
  - linuxkit/runc:b075ab467105ea77a903e4c25633476b5af02054
  - linuxkit/containerd:f392a0c758cca9c2dcf5d60dec2399f49c8eb6f2
  - linuxkit/ca-certificates:ec6a50d1d7110425b4b8d976647094b8d7b6c301
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cc3226a71bdd618fc96ec3f2d1a3d2fe1ac26d78
  - name: dhcpcd
    image: linuxkit/dhcpcd:b8317b466095586c6629edc71f4d490d61ff72cf
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:5628f6141f7e70d8ea8a715b91e7d258271724c0
    env:
     - INSECURE=true
  - name: tss
    image: linuxkit/tss:e68a91f9417105d2d8f1120c10b04bc57b31b2a5
  - name: rngd
    image: linuxkit/rngd:160f9bfafae43b728ab58edd5f3aadc6128d2e55
files:
  - path: etc/getty.shadow
    # sample sets password for root to "abcdefgh" (without quotes)
    contents: 'root:$6$6tPd2uhHrecCEKug$8mKfcgfwguP7f.BLdZsT1Wz7WIIJOBY1oUFHzIv9/O71M2J0EPdtFqFGTxB1UK5ejqQxRFQ.ZSG9YXR0SNsc11:17322:0:::::'
